### ISSUE TITLE
Inconistency CO2 readings between app and wp6003

### ISSUE THREAD

**Issue by arnerek** [zu2/wp6003#3]
Hi,

Thanks for the great work in decoding this device! 

Has there been a change in the latest version of the app (v. 1.2.1 on iOS). Previously I got consistent CO2 reading between App and the python script of this repository. Now I don't anymore. Anyone else observing the same?

Example: 539 ppm with python script, 417 with app.

**Comment by saso5** [comment]
Are you sure you have up-to-date data on your iPhone? As I don't think you can have 2 devices connected to the sensor at the same time.

**Comment by arnerek** [comment]
Yes, I am disconnecting from the iPhone and running the script immediately afterwards.

**Comment by saso5** [comment]
I think the python script still has the 'calibrate' command so this might be causing the problem. See https://github.com/zu2/wp6003/issues/1 for more details.

Try removing it and see if you get numbers that are more equivalent (I've only been testing this with Arduino code)

**Comment by arnerek** [comment]
I don't see the 0xad command in the Python script. This is what you meant?

**Comment by saso5** [comment]
A, sorry didn't check. Then I don't know why you get the different values.
You can also try comparing the values using this tool - https://saso5.github.io/WP6003-air-box/

**Comment by arnerek** [comment]
I tried that one too. Great work btw :) Still difference between the official app. Have you tried the new version of the app that was published a week ago (v.1.2.1)? Because I know that the values was showing good agreement for a while ago.

**Comment by saso5** [comment]
No, I've removed the app and I also don't have an iPhone (android user).  
Maybe they've added some logic that reduces the Co2 value based on your altitude? 🤷‍♂️
(as co2 concentration reduces with altitude)
I also think the CO2 value is complitly irrelevant as it is calculated based on VOC input.

**Comment by maytlim** [comment]
@arnerek, I'm getting a similar difference in reading (130ppm offset in my case). 
>  Now I don't anymore. Anyone else observing the same?
> Example: 539 ppm with python script, 417 with app.

Looking at the app reading immediately after calibration, it seems to be assigning 420ppm as the baseline outdoor value. I'm guessing an offset value equal to the (outdoor) raw sensor reading - 420ppm would then be subtracted by the app from all subsequent CO2 outputs.

**Comment by kudarisenmon** [comment]
> A, sorry didn't check. Then I don't know why you get the different values.
> You can also try comparing the values using this tool - https://saso5.github.io/WP6003-air-box/

I tried your tool, Android app, iOS app and python script and compared the co2 values.

Your tool: 553 ppm
Android app (v1.1.42): 433 ppm
iOS app (v1.2.5): 435 ppm
This python script: 553 ppm

There will be a small margin of error because the measurement requires reconnecting.
The sensor is placed in an empty room with open windows, so values around 420 ppm seem reasonable.
